<?php
$pageTitle='Beyond Market — Create. Sell. Earn.'; require __DIR__.'/includes/header.php';
$products=mread('products.json'); $creators=mread('creators.json'); $q=trim((string)($_GET['q']??'')); $cat=trim((string)($_GET['category']??''));
if($q!=='') $products=array_values(array_filter($products,fn($p)=>stripos(($p['title']??'').' '.($p['creator']??'').' '.($p['category']??''),$q)!==false));
if($cat!=='') $products=array_values(array_filter($products,fn($p)=>(string)($p['category']??'')===$cat));
$cats=['Tattoo Flash','Canvas Prints','Posters','Apparel','Digital Downloads','Creator Tools'];
$previewProducts=array_values(array_filter($products,fn($p)=>!empty($p['image'])));
?>
<main><section class="hero wrap"><div><span class="eyebrow">The creator economy of Beyond OS</span><h1>Create once.<br><span class="gradient">Sell beyond limits.</span></h1><p>Beyond Market connects every creator, app and audience in the ecosystem. Sell art, digital goods, services, templates, music, learning resources and merchandise using cash or bit$.</p><div style="display:flex;gap:11px;flex-wrap:wrap"><a class="btn primary" href="sell.php">Open your storefront →</a><a class="btn" href="../beyond-canvas/">Explore Beyond Canvas</a></div></div><div class="hero-card"><div class="surface"><span>🖼️</span>Physical art</div><div class="surface"><span>⬇️</span>Digital goods</div><div class="surface"><span>🎓</span>Learning</div><div class="surface"><span>🎵</span>Music & media</div></div></section>
<section class="campaign wrap" aria-label="Beyond ecosystem collection"><img src="assets/img/ecosystem-wallet-banner.png" alt="The Beyond ecosystem connected to Wallet"><div class="campaign-copy"><span class="eyebrow">Stencil collection</span><strong>Preview free · Stencil of the Day 100 bit$</strong><a class="btn primary" href="?category=Tattoo+Flash">Browse stencils →</a></div></section>
<section class="section wrap preview-gallery" aria-label="Free asset preview gallery"><div class="section-head"><div><span class="eyebrow">Preview free</span><h2>Explore before you unlock</h2><p class="muted">Browse the carousel freely. Download prices and license terms appear on each asset.</p></div><div class="preview-actions"><button type="button" data-preview-prev aria-label="Previous previews">←</button><button type="button" data-preview-next aria-label="Next previews">→</button></div></div><div class="preview-carousel" data-preview-carousel><?php foreach($previewProducts as $p):?><a class="preview-card" href="product.php?id=<?=urlencode($p['id'])?>"><img src="<?=me($p['image'])?>" alt="Preview of <?=me($p['title'])?>" loading="lazy"><span class="preview-shade"><b><?=me($p['title'])?></b><small>Free preview · <?=number_format((int)$p['price_bits'])?> bit$<?php if(($p['payment_methods']??[])!==['bits']):?> / $<?=me($p['price_cad'])?> CAD<?php endif;?></small></span></a><?php endforeach;?></div></section>
<section class="section wrap"><div class="section-head"><div><span class="eyebrow">Stencil pricing</span><h2>Start daily. Build a collection.</h2></div></div><div class="price-ladder"><div class="panel"><b>100 bit$</b><span>Daily stencil</span></div><div class="panel"><b>500 bit$</b><span>5-stencil pack</span></div><div class="panel"><b>250–500 bit$</b><span>Curated collection</span></div><div class="panel"><b>1,000+ bit$</b><span>Commercial-use pack</span></div></div></section>
<section class="section wrap"><div class="section-head"><div><span class="eyebrow">Browse</span><h2>Made across the ecosystem</h2></div><span class="muted"><?=count($products)?> items</span></div><div class="chips"><a class="chip <?=$cat===''?'active':''?>" href="index.php">All</a><?php foreach($cats as $c):?><a class="chip <?=$cat===$c?'active':''?>" href="?category=<?=urlencode($c)?>"><?=me($c)?></a><?php endforeach;?></div><div class="grid"><?php foreach($products as $p):$bitsOnly=($p['payment_methods']??[])===['bits'];?><article class="panel product"><a href="product.php?id=<?=urlencode($p['id'])?>" style="text-decoration:none"><div class="art" style="--accent:<?=me($p['accent'])?>"><?php if(!empty($p['image'])):?><img src="<?=me($p['image'])?>" alt="<?=me($p['title'])?>" loading="lazy"><?php else:?><?=me($p['emoji'])?><?php endif;?></div><div class="product-body"><span class="eyebrow"><?=me($p['app'])?></span><h3><?=me($p['title'])?></h3><div class="meta">by <?=me($p['creator'])?> · <?=me($p['surface'])?></div><div class="price"><span><?=number_format((int)$p['price_bits'])?> bit$</span><span><?=$bitsOnly?'bit$ only':'$'.me($p['price_cad']).' CAD'?></span></div></div></a></article><?php endforeach;?></div></section>
<section class="section wrap"><div class="section-head"><div><span class="eyebrow">Creators</span><h2>People worth following</h2></div></div><div class="creator-grid"><?php foreach($creators as $c):?><a class="panel creator" href="creator.php?id=<?=urlencode($c['slug'])?>" style="text-decoration:none"><div class="avatar">✦</div><h3><?=me($c['name'])?> <?=$c['verified']?'✓':''?></h3><div class="meta"><?=me($c['role'])?><br><?=me($c['location'])?></div></a><?php endforeach;?></div></section></main>
<?php require __DIR__.'/includes/footer.php'; ?>
<script>(function(){const rail=document.querySelector('[data-preview-carousel]');if(!rail)return;const move=direction=>rail.scrollBy({left:direction*Math.max(280,rail.clientWidth*.72),behavior:'smooth'});document.querySelector('[data-preview-prev]')?.addEventListener('click',()=>move(-1));document.querySelector('[data-preview-next]')?.addEventListener('click',()=>move(1));})();</script>
