<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/app-layout.php';
require_once __DIR__.'/../beyond-tv/includes/youtube-api.php';
bos_require_admin();
$catalogFile=__DIR__.'/../beyond-tv/data/catalog.json';$episodeFile=__DIR__.'/../beyond-tv/data/episodes.json';
$catalog=json_decode((string)@file_get_contents($catalogFile),true)?:[];$episodes=json_decode((string)@file_get_contents($episodeFile),true)?:[];
$shows=array_values(array_filter($catalog,static fn(array $x):bool=>($x['type']??'')==='show'));
$selected=preg_replace('/[^a-z0-9-]/','',strtolower((string)($_GET['show']??$_POST['show_slug']??($shows[0]['slug']??''))));$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $season=max(1,(int)($_POST['season']??1));$episodeNo=max(1,(int)($_POST['episode']??1));$status=(string)($_POST['status']??'Unavailable');
  $allowed=['Full Episode','Clip','Compilation','Trailer','Unavailable'];if(!in_array($status,$allowed,true))$status='Unavailable';
  $youtubeId=beyond_youtube_extract_id((string)($_POST['youtube_id']??''));$metadata=[];
  if($youtubeId!==''){$validation=beyond_youtube_video($youtubeId);if(!($validation['ok']??false)){$error=(string)($validation['error']??'YouTube validation failed.');}else{$metadata=(array)($validation['video']??[]);}}
  if(!$error){$found=false;foreach($episodes as &$item){if(($item['show_slug']??'')===$selected&&(int)($item['season']??0)===$season&&(int)($item['episode']??0)===$episodeNo){$found=true;$item['title']=trim((string)($_POST['title']??''))?:('Episode '.$episodeNo);$item['status']=$status;$item['runtime']=trim((string)($_POST['runtime']??''));$item['air_date']=trim((string)($_POST['air_date']??''));$item['synopsis']=trim((string)($_POST['synopsis']??''));$item['youtube_id']=$youtubeId;$item['source_type']=$youtubeId!==''?'youtube_embed':'none';$item['provider']=$youtubeId!==''?(string)($metadata['channel_title']??'YouTube'):'';$item['thumbnail']=$youtubeId!==''?(string)($metadata['thumbnail']??('https://i.ytimg.com/vi/'.$youtubeId.'/hqdefault.jpg')):'';$item['verified']=$youtubeId!=='';$item['verified_at']=$youtubeId!==''?date('c'):'';break;}}unset($item);
    if(!$found)$error='Episode record not found.';else{$encoded=json_encode($episodes,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);if($encoded===false||file_put_contents($episodeFile,$encoded."\n",LOCK_EX)===false)$error='Unable to save episodes.json.';else$message='Episode catalogue updated.';}
  }
}
$rows=array_values(array_filter($episodes,static fn(array $e):bool=>($e['show_slug']??'')===$selected));usort($rows,static fn($a,$b)=>[(int)$a['season'],(int)$a['episode']]<=>[(int)$b['season'],(int)$b['episode']]);
bos_page_start('TV Episodes','Beyond TV Episode Catalogue','Catalogue every episode and label approved source availability.');?>
<main class="bos-main"><section class="bos-hero"><span class="bos-kicker">Beyond TV 2.2 Beta</span><h1>Episode catalogue</h1><p>Full catalogue records stay visible even when no official full episode is available.</p><?php if($message):?><p class="bos-notice"><?=htmlspecialchars($message)?></p><?php endif;?><?php if($error):?><p class="bos-notice" style="border-color:#ef4444;color:#fecaca"><?=htmlspecialchars($error)?></p><?php endif;?></section>
<section class="bos-section"><form method="get" class="bos-card"><label>Show<select name="show" onchange="this.form.submit()" style="width:100%;padding:12px;margin-top:8px"><?php foreach($shows as $show):?><option value="<?=htmlspecialchars((string)$show['slug'])?>" <?=$selected===($show['slug']??'')?'selected':''?>><?=htmlspecialchars((string)$show['title'])?></option><?php endforeach;?></select></label></form>
<div class="bos-grid"><?php foreach($rows as $row):?><form method="post" class="bos-card"><input type="hidden" name="show_slug" value="<?=htmlspecialchars($selected)?>"><input type="hidden" name="season" value="<?=(int)$row['season']?>"><input type="hidden" name="episode" value="<?=(int)$row['episode']?>"><h2>S<?=str_pad((string)$row['season'],2,'0',STR_PAD_LEFT)?>E<?=str_pad((string)$row['episode'],2,'0',STR_PAD_LEFT)?></h2><label>Title<input name="title" value="<?=htmlspecialchars((string)$row['title'])?>" style="width:100%;padding:10px;margin:6px 0"></label><label>Status<select name="status" style="width:100%;padding:10px;margin:6px 0"><?php foreach(['Full Episode','Clip','Compilation','Trailer','Unavailable'] as $s):?><option <?=$s===($row['status']??'Unavailable')?'selected':''?>><?=htmlspecialchars($s)?></option><?php endforeach;?></select></label><label>YouTube URL or ID<input name="youtube_id" value="<?=htmlspecialchars((string)($row['youtube_id']??''))?>" style="width:100%;padding:10px;margin:6px 0"></label><label>Runtime<input name="runtime" value="<?=htmlspecialchars((string)($row['runtime']??''))?>" style="width:100%;padding:10px;margin:6px 0"></label><label>Air date<input name="air_date" value="<?=htmlspecialchars((string)($row['air_date']??''))?>" style="width:100%;padding:10px;margin:6px 0"></label><label>Synopsis<textarea name="synopsis" rows="3" style="width:100%;padding:10px;margin:6px 0"><?=htmlspecialchars((string)($row['synopsis']??''))?></textarea></label><button class="bos-btn" type="submit">Verify & save</button></form><?php endforeach;?></div></section></main><?php bos_page_end(); ?>
