<?php
declare(strict_types=1);
require_once __DIR__.'/../../includes/ecosystem.php';
$wallet=beyond_app_bootstrap('Beyond Skate');
if(empty($_SESSION['skate_csrf']))$_SESSION['skate_csrf']=bin2hex(random_bytes(32));
$message='';$feedback='';$tone='success';
$tricks=['Ollie','Rolling Ollie','Manual','Pop Shove-it','Kickflip','Heelflip','Drop-in','Frontside 180','Backside 180'];
$modes=['learn'=>'Learn a trick','fix'=>'Fix my attempt','session'=>'Build a session','warmup'=>'Warm-up coach','confidence'=>'Fear and confidence mode','line'=>'Skatepark line planner','safety'=>'Beginner safety mode'];
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!hash_equals((string)$_SESSION['skate_csrf'],(string)($_POST['csrf']??''))){http_response_code(403);exit('Invalid security token.');}
  $trick=in_array((string)($_POST['trick']??''),$tricks,true)?(string)$_POST['trick']:'Ollie';$mode=array_key_exists((string)($_POST['coach_mode']??''),$modes)?(string)$_POST['coach_mode']:'fix';$rating=max(1,min(5,(int)($_POST['rating']??3)));
  if(!isset($_FILES['try_video'])||$_FILES['try_video']['error']!==UPLOAD_ERR_OK){$message='Choose an MP4, MOV, or WebM clip of your attempt.';$tone='error';}
  elseif((int)$_FILES['try_video']['size']>50*1024*1024){$message='That video is over the private 50 MB V1 upload limit.';$tone='error';}
  else{
    $finfo=new finfo(FILEINFO_MIME_TYPE);$mime=(string)$finfo->file($_FILES['try_video']['tmp_name']);$allowed=['video/mp4'=>'mp4','video/quicktime'=>'mov','video/webm'=>'webm'];
    if(!isset($allowed[$mime])){$message='Use an MP4, MOV, or WebM video.';$tone='error';}
    else{
      $privateDir=beyond_private_root().'/skate-attempts';if(!is_dir($privateDir)&&!mkdir($privateDir,0700,true)&&!is_dir($privateDir))throw new RuntimeException('Unable to create private attempt storage.');
      $attemptId=date('Ymd-His').'-'.bin2hex(random_bytes(6));$filename=$attemptId.'.'.$allowed[$mime];$target=$privateDir.'/'.$filename;
      if(!move_uploaded_file($_FILES['try_video']['tmp_name'],$target)){$message='The private upload could not be saved. Check folder permissions.';$tone='error';}
      else{
        @chmod($target,0600);$entry=['id'=>$attemptId,'user_id'=>(int)($_SESSION['user_id']??0),'trick'=>$trick,'coach_mode'=>$mode,'self_rating'=>$rating,'private_file'=>$filename,'mime'=>$mime,'size'=>(int)$_FILES['try_video']['size'],'privacy'=>'private','analysis_status'=>'queued','created_at'=>date(DATE_ATOM)];file_put_contents($privateDir.'/attempts.jsonl',json_encode($entry,JSON_UNESCAPED_SLASHES).PHP_EOL,FILE_APPEND|LOCK_EX);
        $message='Private attempt saved. Your V1 coach review is ready and full motion analysis is queued.';
        if($trick==='Ollie'||$trick==='Rolling Ollie')$feedback=$rating<=2?'Coach focus: keep your shoulders over the board, let the tail contact the ground before sliding the front foot, and practise ten controlled pops without chasing height.':($rating===3?'Coach focus: keep the same foot placement for five attempts and aim to land over the bolts before adding speed.':'Coach focus: build consistency. Compare the latest landing with your cleanest clip, then add controlled speed or a small obstacle.');
        else $feedback=$rating<=2?'Coach focus: return to the prerequisite movement, reduce speed, use protective gear, and film one clear side angle.':($rating===3?'Coach focus: change only one variable—foot placement, timing, or shoulder alignment—during the next five attempts.':'Coach focus: repeat the trick under control and measure clean landings, not risk.');
      }
    }
  }
}
$beginner=['Skateboard parts','Safety and protective gear','Standing on the board','Pushing','Turning','Stopping','Riding off a curb','Tic-tacs','Manual basics','Ollie preparation'];
$street=['Ollie','Fakie ollie','Frontside 180','Backside 180','Pop shove-it','Kickflip','Heelflip','Boardslide','50-50 grind','Stair and gap progression'];
$park=['Pumping','Dropping in','Kick turns','Rock to fakie','Axle stall','Bowl carving','Mini-ramp basics','Air and coping progression'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Beyond Skate — Learn tricks, design boards and level up</title><meta name="description" content="Beyond Skate combines a safety-first AI coach, custom board designer, Skate Academy, mini games, progression, community, and Beyond bit$."><meta name="theme-color" content="#080b16"><link rel="icon" type="image/webp" href="/assets/icons/beyond-skate-192.webp"><link rel="stylesheet" href="/beyond-health/beyond-skate/assets/app.css"></head><body>
<header class="skate-nav"><a class="skate-brand" href="/beyond-health/"><img src="/assets/icons/beyond-skate-192.webp" alt=""><strong>Beyond Health / Beyond Skate</strong></a><nav><a href="#coach">AI Coach</a><a href="#designer">Board Designer</a><a href="#academy">Academy</a><a href="#games">Mini Games</a><a class="skate-button small" href="#v1">V1 Roadmap</a></nav></header>
<main id="top"><section class="skate-hero skate-shell"><div><span class="skate-kicker">🛹 AI COACH · DESIGN · LEARN · PLAY</span><h1>Learn tricks.<br><em>Design boards.</em><br>Level up.</h1><p>Beyond Skate feels like a digital skatepark: practise safely, learn in the right order, keep the makes and misses, create your setup, play skill games, and earn progress for consistency—not reckless risk.</p><div class="hero-actions"><a class="skate-button" href="#coach">Upload an attempt</a><a class="skate-button ghost" href="#academy">Explore Skate Academy</a></div><div class="rank-line"><span>First Push</span><i></i><span>Sidewalk Rider</span><i></i><span>Park Regular</span><i></i><span>Beyond Skater</span></div></div><aside class="profile-card"><header><div><small>SKATER PROFILE</small><h2>Session ready</h2></div><span class="level">LV 08</span></header><div class="profile-board"><div class="mini-deck"><span>BEYOND</span></div></div><dl><div><dt>Current goal</dt><dd>Rolling ollie</dd></div><div><dt>Safe streak</dt><dd>6 sessions</dd></div><div><dt>Beyond bit$</dt><dd><?=number_format((int)($wallet['balance']??0))?></dd></div></dl><div class="profile-progress"><span></span></div><small>420 XP to Park Regular</small></aside></section>
<section class="pillar-grid skate-shell"><article><span>🤖</span><h2>AI Skate Coach</h2><p>Private attempt journal, focused feedback, session plans, confidence support, safety gates, and future motion analysis.</p><a href="#coach">Open coach →</a></article><article><span>🎨</span><h2>Board Designer</h2><p>Create deck concepts, colours, grip tape, wheels, graphics, and setup recommendations in a live 2D preview.</p><a href="#designer">Design a board →</a></article><article><span>🎓</span><h2>Skate Academy</h2><p>Beginner, street, and park paths that teach prerequisites before harder tricks.</p><a href="#academy">See paths →</a></article><article><span>🎮</span><h2>Mini Games</h2><p>Train ollie timing, recognize tricks, build lines, practise balance, and learn board setups.</p><a href="#games">Play V1 games →</a></article></section>
<section class="feature-section dark-section" id="coach"><div class="skate-shell"><div class="section-heading"><span class="skate-kicker">PRIVATE V1 COACH</span><h2>Film the attempt. Focus the next one.</h2><p>New clips are stored outside the public website. Immediate feedback is a safety-first V1 motion review; full frame-by-frame computer vision remains on the later roadmap.</p></div><div class="coach-layout"><form class="skate-panel upload-panel" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=htmlspecialchars((string)$_SESSION['skate_csrf'])?>"><h3>Upload a private attempt</h3><?php if($message):?><div class="skate-notice <?=$tone?>"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($feedback):?><div class="coach-feedback"><strong>Coach focus</strong><p><?=htmlspecialchars($feedback)?></p></div><?php endif;?><label>Coach mode<select name="coach_mode"><?php foreach($modes as $value=>$label):?><option value="<?=htmlspecialchars($value)?>"><?=htmlspecialchars($label)?></option><?php endforeach;?></select></label><label>Trick<select name="trick"><?php foreach($tricks as $trick):?><option><?=htmlspecialchars($trick)?></option><?php endforeach;?></select></label><label>How did it feel?<select name="rating"><option value="1">1 — I need the basics</option><option value="2">2 — Learning the motion</option><option value="3" selected>3 — Almost there</option><option value="4">4 — Landed, not consistent</option><option value="5">5 — Clean and controlled</option></select></label><label>Attempt video<input type="file" name="try_video" accept="video/mp4,video/quicktime,video/webm" required><small>MP4, MOV, or WebM · 50 MB maximum · private by default</small></label><button class="skate-button" type="submit">Save attempt + review</button></form><div class="skate-panel analysis-panel"><h3>Motion analysis plan</h3><div class="analysis-grid"><span>Foot placement</span><span>Shoulder rotation</span><span>Pop timing</span><span>Board angle</span><span>Landing balance</span><span>Speed and approach</span></div><div class="comparison"><div><b>First</b><small>Baseline</small></div><div><b>Best</b><small>Reference</small></div><div><b>Latest</b><small>Compare</small></div></div><h3>Suggested session</h3><ol><li><b>5 min</b> pushing, carving, rolling squats</li><li><b>10</b> stationary ollie attempts</li><li><b>5</b> rolling ollies</li><li><b>3</b> attempts over a small safe marker</li><li><b>Finish</b> with one trick you already enjoy</li></ol></div></div></div></section>
<section class="feature-section skate-shell" id="designer"><div class="section-heading"><span class="skate-kicker">CUSTOM 2D BOARD DESIGNER</span><h2>Make the deck yours.</h2><p>Build an editable concept now. 3D rotation, AI artwork generation, component shopping, and print-on-demand ordering are staged for later releases.</p></div><div class="designer-layout"><div class="board-stage"><div class="deck-preview" id="deck-preview"><div class="deck-art" id="deck-art"></div><strong id="deck-text">BEYOND</strong><div class="truck top"></div><div class="truck bottom"></div><i class="wheel w1"></i><i class="wheel w2"></i><i class="wheel w3"></i><i class="wheel w4"></i></div></div><form class="skate-panel designer-controls" onsubmit="return false"><label>Concept prompt<input id="design-prompt" value="Purple cosmic eye skateboard with a glowing keyhole"></label><button class="skate-button" id="concept-button" type="button">Generate concept</button><div class="control-grid"><label>Deck colour<input id="deck-color" type="color" value="#6d36e7"></label><label>Graphic colour<input id="art-color" type="color" value="#47d8ff"></label><label>Wheel colour<input id="wheel-color" type="color" value="#f6d44b"></label><label>Deck text<input id="board-text" value="BEYOND" maxlength="16"></label></div><label>Graphic style<select id="graphic-style"><option value="keyhole">Glowing keyhole</option><option value="eye">Cosmic eye</option><option value="horus">Eye of Horus</option><option value="city">Anime city</option><option value="flash">Tattoo flash</option></select></label><div class="setup-note"><strong>Board Build Assistant</strong><p>V1 guidance: most street beginners can start around 8.0–8.25 inches. Final recommendations should also consider shoe size, height, terrain, tricks, and budget.</p></div></form></div></section>
<section class="feature-section academy-section" id="academy"><div class="skate-shell"><div class="section-heading"><span class="skate-kicker">SKATE ACADEMY</span><h2>Progression before pressure.</h2><p>Every lesson format is designed for short video, foot-placement diagram, voice tutorial, safety warning, practice checklist, assessment, quiz, challenge, and badge.</p></div><div class="path-grid"><article><header><span>01</span><div><small>FOUNDATION</small><h3>Beginner Path</h3></div></header><ol><?php foreach($beginner as $lesson):?><li><?=htmlspecialchars($lesson)?></li><?php endforeach;?></ol><a class="skate-button" href="#coach">Begin safely</a></article><article><header><span>02</span><div><small>TRICK BUILDING</small><h3>Street Path</h3></div></header><ol><?php foreach($street as $lesson):?><li><?=htmlspecialchars($lesson)?></li><?php endforeach;?></ol><a class="skate-button ghost" href="#coach">Assess prerequisites</a></article><article><header><span>03</span><div><small>TRANSITIONS</small><h3>Park Path</h3></div></header><ol><?php foreach($park as $lesson):?><li><?=htmlspecialchars($lesson)?></li><?php endforeach;?></ol><a class="skate-button ghost" href="#coach">Plan a park session</a></article></div><aside class="safety-banner"><strong>🪖 No “kickflip on day one” chaos.</strong><span>Protective gear, spotters, park rules, dry surfaces, and prerequisite control come before progression. Beyond bit$ never reward reckless attempts.</span></aside></div></section>
<section class="feature-section skate-shell" id="games"><div class="section-heading"><span class="skate-kicker">MINI GAMES</span><h2>Train timing and skate knowledge.</h2></div><div class="game-grid"><article class="playable-game"><span>1</span><h3>Ollie Timing</h3><p>Tap when the marker reaches the landing zone. Better timing earns a cleaner ollie.</p><div class="timing-track"><i id="timing-marker"></i><b></b></div><button class="skate-button" id="timing-button">Start timing</button><strong id="timing-score">Ready</strong></article><article class="playable-game"><span>2</span><h3>Trick Match</h3><p id="trick-question">Which trick begins with a tail pop and a 180° horizontal board rotation?</p><div class="trick-options" id="trick-options"></div><strong id="trick-result">Choose an answer</strong></article><article><span>3</span><h3>Skate Line Builder</h3><p>Arrange ramps, rails, stairs, and ledges into a playable line and real session plan.</p><b>V1 planner next</b></article><article><span>4</span><h3>S.K.A.T.E.</h3><p>Skill-matched games against AI characters, friends, local skaters, or classmates.</p><b>Later release</b></article><article><span>5</span><h3>Balance Challenge</h3><p>Use phone motion sensors for manuals, nose manuals, rail balance, and drop-in posture.</p><b>Sensor beta later</b></article><article><span>6</span><h3>Build-a-Board</h3><p>Assemble the right setup for a street skater, child, vert skater, cruiser, or technical skater.</p><b>Learning game planned</b></article><article><span>7</span><h3>Skate Shop Simulator</h3><p>Design boards, price products, sponsor skaters, organize competitions, and build a team.</p><b>Beyond Earn expansion</b></article></div></section>
<section class="feature-section community-section"><div class="skate-shell community-layout"><div><span class="skate-kicker">COMMUNITY + PRIVACY</span><h2>Find your crew without giving away your location.</h2><p>Trick of the day, progress clips, crews, challenges, deck designs, park reviews, and competition listings can connect skaters. For younger users, profiles start private; location sharing stays optional and approximate by default.</p><div class="privacy-chips"><span>Private youth profiles</span><span>Approximate location</span><span>Parent controls</span><span>Report + block</span><span>No reckless rewards</span></div></div><aside class="bits-card"><small>BEYOND BITS</small><h3>Earn for consistency.</h3><ul><li>Complete lessons and quizzes</li><li>Practise safely</li><li>Maintain a session streak</li><li>Track improvement</li><li>Join community challenges</li><li>Design popular boards</li></ul><p>Unlock graphics, coaching sessions, avatar gear, park objects, components, and merchandise.</p></aside></div></section>
<section class="feature-section skate-shell" id="v1"><div class="section-heading"><span class="skate-kicker">RELEASE ROADMAP</span><h2>A focused first push.</h2></div><div class="roadmap-grid"><article><span>V1</span><h3>Strong first release</h3><ul><li>Skate profile and skill assessment</li><li>Beginner Academy</li><li>Private Ollie coach uploads</li><li>Trick progress journal</li><li>Custom 2D board designer</li><li>Ollie Timing and Trick Match</li><li>Daily skate challenge</li><li>Beyond bit$ rewards</li><li>Session planner</li></ul></article><article><span>NEXT</span><h3>Later releases</h3><ul><li>Full AI trick recognition</li><li>3D board designer</li><li>Online S.K.A.T.E.</li><li>Skate shop simulator</li><li>Local park discovery</li><li>Physical board ordering</li><li>AR foot-placement guide</li><li>Wearable and motion support</li></ul></article></div></section></main><footer class="skate-footer"><strong>Beyond Skate</strong><span>Learn tricks, design boards and level up your skating. 🛹</span><a href="/beyond-health/">Beyond Health</a></footer><script src="/beyond-health/beyond-skate/assets/app.js"></script></body></html>
