<?php
declare(strict_types=1);
require_once __DIR__ . '/require-member.php';

$catalog = json_decode((string) file_get_contents(__DIR__ . '/data/catalog.json'), true) ?: [];
$episodes = json_decode((string) @file_get_contents(__DIR__ . '/data/episodes.json'), true) ?: [];
$slug = preg_replace('/[^a-z0-9-]/', '', strtolower((string)($_GET['slug'] ?? '')));
$title = null; foreach ($catalog as $candidate) { if (($candidate['slug'] ?? '') === $slug) { $title = $candidate; break; } }
if (!$title) { http_response_code(404); $title = ['title'=>'Title unavailable','description'=>'This title could not be found.','type'=>'show','icon'=>'📺','gradient'=>'linear-gradient(135deg,#111,#444)','source_type'=>'none']; }
$sourceType = (string)($title['source_type'] ?? 'none');
$youtubeId = preg_replace('/[^A-Za-z0-9_-]/', '', (string)($title['youtube_id'] ?? ''));
$youtubeStart = max(0, (int)($title['youtube_start'] ?? 0));
$params = http_build_query(['autoplay'=>!empty($title['autoplay'])?1:0,'mute'=>!empty($title['muted'])?1:0,'playsinline'=>1,'rel'=>0,'start'=>$youtubeStart]);
$youtubePlaylistId = preg_replace('/[^A-Za-z0-9_-]/', '', (string)($title['youtube_playlist_id'] ?? ''));
$playlistEpisodeCount=max(0,(int)($title['playlist_episode_count']??0));
$selectedEpisode=max(1,min($playlistEpisodeCount?:1,(int)($_GET['episode']??1)));
$archiveId = preg_replace('/[^A-Za-z0-9_.-]/', '', (string)($title['archive_id'] ?? ''));
$showEpisodes = array_values(array_filter($episodes, static fn(array $e): bool => ($e['show_slug'] ?? '') === $slug));
usort($showEpisodes, static fn(array $a,array $b): int => [(int)$a['season'],(int)$a['episode']] <=> [(int)$b['season'],(int)$b['episode']]);
$seasons=[]; foreach($showEpisodes as $episode){$seasons[(int)$episode['season']][]=$episode;}
$statusLabels=['Full Episode'=>'Full Episode','Clip'=>'Clip','Compilation'=>'Compilation','Trailer'=>'Trailer','Unavailable'=>'Unavailable'];
?>
<!doctype html><html lang="en"><head><script>(function(){try{const t=localStorage.getItem("beyond-tv-theme");document.documentElement.dataset.tvTheme=["dark","light","sunset"].includes(t)?t:"dark"}catch(e){document.documentElement.dataset.tvTheme="dark"}})();</script><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?=htmlspecialchars((string)$title['title'])?> | Beyond TV</title><link rel="stylesheet" href="/beyond-tv/assets/css/app.css?v=2.2.0"></head><body class="tv-app"><?php include __DIR__.'/partials/header.php'; ?>
<main class="page shell title-page"><a class="back app-back" href="/beyond-tv/browse.php">← Browse</a>
<section class="title-layout" id="player"><div class="title-player">
<?php if($sourceType==='youtube_embed' && $youtubeId): ?><div class="youtube-player-wrap"><iframe class="youtube-player" src="https://www.youtube-nocookie.com/embed/<?=htmlspecialchars($youtubeId)?>?<?=htmlspecialchars($params)?>" title="<?=htmlspecialchars((string)$title['title'])?>" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
<?php elseif($sourceType==='youtube_playlist_embed' && $youtubePlaylistId): ?><div class="youtube-player-wrap library-playlist-player"><iframe class="youtube-player" src="https://www.youtube-nocookie.com/embed/videoseries?list=<?=htmlspecialchars($youtubePlaylistId)?>&index=<?=max(0,$selectedEpisode-1)?>&playsinline=1&rel=0&modestbranding=1" title="<?=htmlspecialchars((string)$title['title'])?> Season 1 playlist" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
<?php elseif($sourceType==='archive_embed' && $archiveId): ?><div class="youtube-player-wrap"><iframe class="youtube-player" src="https://archive.org/embed/<?=htmlspecialchars($archiveId)?>" title="<?=htmlspecialchars((string)$title['title'])?>" allow="autoplay; fullscreen" allowfullscreen></iframe></div>
<?php elseif($sourceType==='direct_video' && !empty($title['video_url'])): ?><div class="provider-player title-video"><video class="beyond-video" controls playsinline preload="metadata" src="<?=htmlspecialchars((string)$title['video_url'])?>"></video></div>
<?php else: ?><div class="external-player" style="background:<?=htmlspecialchars((string)$title['gradient'])?>"><span class="external-icon"><?=htmlspecialchars((string)$title['icon'])?></span><h2>Catalogue available</h2><p>No approved full-show source has been added. Browse the episode availability below.</p></div><?php endif; ?>
</div><aside class="title-info"><span class="source-pill"><?=($title['type']??'')==='movie'?'FREE MOVIE':'TV SHOW'?></span><h1><?=htmlspecialchars((string)$title['title'])?></h1><p class="title-meta"><?=htmlspecialchars((string)($title['year']??''))?> · <?=htmlspecialchars((string)($title['rating']??'NR'))?><?php if(!empty($title['runtime'])):?> · <?=htmlspecialchars((string)$title['runtime'])?><?php endif;?></p><p><?=htmlspecialchars((string)($title['description']??''))?></p><p><strong><?=htmlspecialchars((string)($title['genre']??''))?></strong></p><?php if(($title['type']??'')==='show'):?><?php if($sourceType==='youtube_playlist_embed'):?><p class="catalog-summary"><strong>Season 1 library</strong> · Choose any episode from the complete episode list below.</p><?php else:?><p class="catalog-summary"><strong><?=count($seasons)?> seasons</strong> · <?=count($showEpisodes)?> episode records</p><?php endif;?><?php endif;?><?php if(!empty($title['source_label'])):?><p class="source-note"><span class="source-pill"><?=htmlspecialchars(strtoupper((string)$title['source_label']))?></span></p><?php endif;?><?php if(!empty($title['youtube_playlist_id'])): ?><a class="btn btn-secondary" target="_blank" rel="noopener" href="https://www.youtube.com/playlist?list=<?=htmlspecialchars((string)$title['youtube_playlist_id'])?>">Open official collection ↗</a><?php endif; ?></aside></section>
<?php if(($title['type']??'')==='show' && $sourceType==='youtube_playlist_embed' && $youtubePlaylistId && $playlistEpisodeCount>0):?>
<section class="episode-catalog season-library" aria-labelledby="season-library-heading"><div class="episode-heading"><div><span class="kicker">SEASON 1 LIBRARY</span><h2 id="season-library-heading">All episodes</h2></div><p>Select an episode here. Beyond TV loads it directly in the player above—no playlist menu required.</p></div>
<div class="season-library-grid"><?php for($episodeNumber=1;$episodeNumber<=$playlistEpisodeCount;$episodeNumber++):?><a class="season-episode-card <?=$episodeNumber===$selectedEpisode?'is-playing':''?>" href="/beyond-tv/title.php?slug=<?=urlencode($slug)?>&amp;episode=<?=$episodeNumber?>#player" aria-current="<?=$episodeNumber===$selectedEpisode?'true':'false'?>"><span class="episode-index">S01E<?=str_pad((string)$episodeNumber,2,'0',STR_PAD_LEFT)?></span><strong>Episode <?=$episodeNumber?></strong><span><?=$episodeNumber===$selectedEpisode?'Now selected':'Play episode'?> ▶</span></a><?php endfor;?></div></section>
<?php endif; ?>
<?php if(($title['type']??'')==='show' && !empty($seasons)):?><section class="episode-catalog" aria-labelledby="episodes-heading"><div class="episode-heading"><div><span class="kicker">EPISODE CATALOGUE</span><h2 id="episodes-heading">Seasons & episodes</h2></div><p>Availability reflects approved sources, not whether the episode exists commercially.</p></div>
<?php foreach($seasons as $seasonNumber=>$seasonEpisodes):?><details class="season-panel" <?=$seasonNumber===1?'open':''?>><summary><strong>Season <?=intval($seasonNumber)?></strong><span><?=count($seasonEpisodes)?> episodes</span></summary><div class="episode-list">
<?php foreach($seasonEpisodes as $episode): $status=(string)($episode['status']??'Unavailable'); $playable=($episode['source_type']??'none')!=='none'; ?><article class="episode-row"><div class="episode-number">S<?=str_pad((string)$episode['season'],2,'0',STR_PAD_LEFT)?>E<?=str_pad((string)$episode['episode'],2,'0',STR_PAD_LEFT)?></div><div class="episode-copy"><h3><?=htmlspecialchars((string)$episode['title'])?></h3><p><?=htmlspecialchars((string)($episode['synopsis']?:'Episode record catalogued. Approved playback details have not yet been added.'))?></p><small><?=htmlspecialchars((string)($episode['air_date']??''))?><?=!empty($episode['runtime'])?' · '.htmlspecialchars((string)$episode['runtime']):''?></small></div><div class="episode-actions"><span class="availability status-<?=strtolower(str_replace(' ','-', $status))?>"><?=htmlspecialchars($statusLabels[$status]??$status)?></span><?php if($playable && !empty($episode['youtube_id'])):?><a class="episode-play" target="_blank" rel="noopener" href="https://www.youtube.com/watch?v=<?=htmlspecialchars((string)$episode['youtube_id'])?>">Watch source ↗</a><?php else:?><span class="episode-unavailable">No approved source</span><?php endif;?></div></article><?php endforeach; ?></div></details><?php endforeach; ?>
</section><?php endif; ?>
</main><?php include __DIR__.'/partials/footer.php'; ?></body></html>
