<?php
declare(strict_types=1);
function beyond_tv_eight_channel_guide(array $classicState, array $cartoonState): array {
    $static = function(string $slug,string $name,string $icon,string $access,array $rows): array { return compact('slug','name','icon','access','rows'); };
    return [
      ['slug'=>'classic-cartoon-theater','name'=>'Classic Cartoons','icon'=>'🎞️','access'=>'Free · Live','rows'=>$classicState['blocks']],
      ['slug'=>'beyond-cartoons','name'=>'Beyond Cartoons','icon'=>'📺','access'=>'Free · Live','rows'=>$cartoonState['blocks']],
      $static('bubble-guppies','Preschool TV','🐾','Free · YouTube',[
        ['start'=>0,'end'=>3,'icon'=>'🌙','title'=>'Sleepy-Time Preschool','lineup'=>'Gentle Bluey moments · calming nursery stories'],['start'=>3,'end'=>6,'icon'=>'💤','title'=>'Dreamy Adventures','lineup'=>'Quiet preschool stories and soft learning songs'],['start'=>6,'end'=>9,'icon'=>'🐾','title'=>'Breakfast with Bluey','lineup'=>'Bluey full episodes · imagination and family fun'],['start'=>9,'end'=>12,'icon'=>'🎵','title'=>'Sing & Learn','lineup'=>'Bubble Guppies music · numbers · shapes'],['start'=>12,'end'=>15,'icon'=>'💙','title'=>'Bluey Playtime','lineup'=>'Official Bluey full-episode compilation'],['start'=>15,'end'=>18,'icon'=>'🫧','title'=>'Bubble Guppies','lineup'=>'Underwater adventures and preschool learning'],['start'=>18,'end'=>21,'icon'=>'⭐','title'=>'Preschool Prime Time','lineup'=>'Bluey · Bubble Guppies · family favourites'],['start'=>21,'end'=>24,'icon'=>'🌙','title'=>'Bedtime Pups','lineup'=>'Calmer Bluey stories before bed']]),
      $static('space-tv','Beyond Space','🛰️','Free · YouTube',[
        ['start'=>0,'end'=>3,'icon'=>'🌌','title'=>'Milky Way Overnight','lineup'=>'Sleep-time Milky Way ambience and calming galaxy visuals'],['start'=>3,'end'=>6,'icon'=>'☀️','title'=>'The Sun in 4K','lineup'=>'The deepest views into the Sun · SDO 4K'],['start'=>6,'end'=>9,'icon'=>'🌅','title'=>'Sun 101','lineup'=>'A clear introduction to our nearest star'],['start'=>9,'end'=>12,'icon'=>'✨','title'=>'Milky Way Explorer','lineup'=>'Stars, structure and the galaxy we call home'],['start'=>12,'end'=>15,'icon'=>'🌞','title'=>'Solar Activity','lineup'=>'How activity on the Sun shapes our world'],['start'=>15,'end'=>18,'icon'=>'🌠','title'=>'Journey Through the Milky Way','lineup'=>'Galactic structure and cosmic discovery'],['start'=>18,'end'=>21,'icon'=>'⭐','title'=>'Sun Prime Time','lineup'=>'Solar Activity · Sun 101 · SDO 4K'],['start'=>21,'end'=>24,'icon'=>'🔭','title'=>'Galactic Night','lineup'=>'Sleep-time Milky Way ambience for winding down']]),
      $static('beyond-ancient','Beyond Ancient','𓂀','Free · YouTube',[
        ['start'=>0,'end'=>3,'icon'=>'🏺','title'=>'Ancient Egypt After Dark','lineup'=>'Pharaohs, temples and tomb discoveries'],['start'=>3,'end'=>6,'icon'=>'📜','title'=>'Dynasties of the Nile','lineup'=>'Early kingdoms through the New Kingdom'],['start'=>6,'end'=>9,'icon'=>'☀️','title'=>'Dawn of Civilization','lineup'=>'The Nile, farming, writing and cities'],['start'=>9,'end'=>12,'icon'=>'🔺','title'=>'Pyramid Engineering','lineup'=>'How Egypt built an epic empire'],['start'=>12,'end'=>15,'icon'=>'👑','title'=>'Pharaohs & Queens','lineup'=>'Royal power, Cleopatra and Nefertiti'],['start'=>15,'end'=>18,'icon'=>'⚱️','title'=>'Tombs & Afterlife','lineup'=>'Mummification and the Book of the Dead'],['start'=>18,'end'=>21,'icon'=>'🏛️','title'=>'Egypt Prime Documentary','lineup'=>'Featured Egyptian-history documentary'],['start'=>21,'end'=>24,'icon'=>'🔦','title'=>'Archaeology Night','lineup'=>'Lost cities, excavations and new discoveries']]),
      $static('classic-cinema','Beyond Movies','🎬','Free · Scheduled',[
        ['start'=>0,'end'=>24,'icon'=>'🎬','title'=>'Feature of the Day','lineup'=>'Mon Cats · Tue Mud · Wed Never Back Down · Thu Big Stan · Fri In the Mix · Sat Don’t Look Away · Sun Marathon']]),
      $static('beyond-french','Beyond French','🇫🇷','Free · YouTube',[
        ['start'=>0,'end'=>3,'icon'=>'🌙','title'=>'French Listening','lineup'=>'Slow French and pronunciation practice'],['start'=>3,'end'=>6,'icon'=>'🎧','title'=>'Vocabulary Loop','lineup'=>'Everyday words and useful phrases'],['start'=>6,'end'=>9,'icon'=>'🥐','title'=>'Bonjour Morning','lineup'=>'Greetings and beginner essentials'],['start'=>9,'end'=>12,'icon'=>'📘','title'=>'French Foundations','lineup'=>'Grammar, numbers and introductions'],['start'=>12,'end'=>15,'icon'=>'🗣️','title'=>'Conversation Practice','lineup'=>'Real-life dialogues and speaking drills'],['start'=>15,'end'=>18,'icon'=>'✍️','title'=>'Grammar Workshop','lineup'=>'Verbs, articles and sentence building'],['start'=>18,'end'=>21,'icon'=>'🇫🇷','title'=>'Français du Jour','lineup'=>'Daily lesson and cultural notes'],['start'=>21,'end'=>24,'icon'=>'✅','title'=>'Review & Quiz','lineup'=>'Recap, listening check and vocabulary review']]),
      $static('beyond-health','Beyond Health','💚','Free · YouTube',[
        ['start'=>0,'end'=>24,'icon'=>'💚','title'=>'Featured Health Presentation','lineup'=>'New Channel 8 feature · YouTube video 7_chERnJ0gE']])
    ];
}
function beyond_tv_guide_block(array $rows,int $hour): array { foreach($rows as $row){if($hour >= (int)$row['start'] && $hour < (int)$row['end']) return $row;} return $rows[0]; }
